### PR TITLE
Rev B

### PR DESCRIPTION
**Pull request by SyrianSpock**
This PR adds fixes for the two main issues reported regarding DFU and the reset pin.

[Schematics](https://github.com/cvra/uwb-beacon-board/blob/revB/beacon.pdf)
[Gerber files](https://github.com/cvra/uwb-beacon-board/files/1693107/gerber.zip)

### CODE REVIEW

**Comment by antoinealb** [comment]
Just looked at the schematics, and PA10 is still a USB pin (ID pin apparently). Is that an issue ?

**Comment by SyrianSpock** [comment]
> Just looked at the schematics, and PA10 is still a USB pin (ID pin apparently). Is that an issue ?

Moved to PC9 just to be sure.

**Comment by vieillemaison** [comment]
- Soldermask top and bottom is in my opinon to much oversized
- Silkscreen SW2 out of PCB border
- Silkscreen Text Status and Debug are placed over SMD pad of R12
- W1-W8 are considered as test point but are covered by soldermask
- W5-W8 are not identified by silkscreen
- Add several via in GND plan to avoid to have large zones on bottom copper side without any copper
- Is this correct that there is an copper exclusion zone under the IMU?

**Comment by SyrianSpock** [comment]
> - Soldermask top and bottom is in my opinion to much oversized

I used the same settings as rev 1.0, do you think this is an issue? Seeedstudio has never complained.

> - Silkscreen SW2 out of PCB border
> - Silkscreen Text Status and Debug are placed over SMD pad of R12

Good catch, I fixed these. Moved the mechanical drawing of SW2 to the user drawings layer.

> - W1-W8 are considered as test point but are covered by soldermask

That's intended, they're treated as pads, so we can solder wires on them to analyse the signals.

> - W5-W8 are not identified by silkscreen

I double checked, and they are identified on the silkscreen (see below the vias that carry the signals from the pads), also visible on seeedstudio's gerber viewer.

> - Add several via in GND plane to avoid to have large zones on bottom copper side without any copper

Thanks for pointing this out, I added a few GND vias. 

> - Is this correct that there is an copper exclusion zone under the IMU?

Yes, this is recommended by the manufacturer to avoid hindering performance of the chip

screenshot from 2018-02-04 16 43 25

**Comment by vieillemaison** [comment]
There are still areas that can be filled with copper check picture:
image
For the soldermask opening based on seeedstudio guideline below it's 3mil or 0.08mm around the pads and minimum soldermask dam of 0.32mm (without extra costs):
image

**Comment by SyrianSpock** [comment]
Added suggested vias, but I still don't see the issue with the solder mask, there is 0.2mm clearance from each side of the pads (higher than the minimum 0.08mm required). Is there something I'm missing here?

**Pull request merged**
